const assert = require("node:assert/strict");
const { mkdir, mkdtemp, readFile, rm, writeFile } = require("node:fs/promises");
const os = require("node:os");
const path = require("node:path");
const { spawnSync } = require("node:child_process");
const test = require("node:test");

const repoRoot = path.resolve(__dirname, "..");
const cliPath = path.join(repoRoot, "dist", "cli", "index.js");

function runCli(cwd, args) {
  return spawnSync(process.execPath, [cliPath, ...args], {
    cwd,
    encoding: "utf8"
  });
}

async function writeFixture(root, relativePath, content) {
  const fullPath = path.join(root, relativePath);
  await mkdir(path.dirname(fullPath), { recursive: true });
  await writeFile(fullPath, content, "utf8");
}

async function withLogRepo(callback) {
  const tempDir = await mkdtemp(path.join(os.tmpdir(), "repo-context-center-log-"));

  try {
    await writeFixture(tempDir, "package.json", "{\"name\":\"fixture\",\"scripts\":{\"test\":\"node --test\"}}\n");
    await writeFixture(tempDir, "src/auth.ts", "export function login() { return true; }\n");
    await writeFixture(
      tempDir,
      "docs/ai-context/CHANGE_LOG.md",
      [
        "# Change Log",
        "",
        "Track meaningful context changes.",
        "",
        "<!-- repo-context-center:generated:start -->",
        "## Generated Repo Map",
        "",
        "| Date | Command | Files updated | Reason |",
        "| --- | --- | --- | --- |",
        "| 2026-01-01 | `repo-context-center map --write` | 13 context files | generated repo-specific context map |",
        "",
        "_Generated by repo-context-center. Edit outside this section._",
        "<!-- repo-context-center:generated:end -->",
        ""
      ].join("\n")
    );

    return await callback(tempDir);
  } finally {
    await rm(tempDir, { recursive: true, force: true });
  }
}

test("log adds a durable changelog entry before generated content", async () => {
  await withLogRepo(async (tempDir) => {
    const result = runCli(tempDir, ["log", "Fixed auth routing", "--files", "src/auth.ts,tests/auth.test.ts"]);
    const content = await readFile(path.join(tempDir, "docs", "ai-context", "CHANGE_LOG.md"), "utf8");

    assert.equal(result.status, 0);
    assert.equal(result.stdout, "Updated docs/ai-context/CHANGE_LOG.md\n");
    assert.match(content, /## Manual Entries/);
    assert.match(content, /\| Date \| Summary \| Files \|/);
    assert.match(content, /\| \d{4}-\d{2}-\d{2} \| Fixed auth routing \| `src\/auth\.ts`, `tests\/auth\.test\.ts` \|/);
    assert.ok(content.indexOf("Fixed auth routing") < content.indexOf("<!-- repo-context-center:generated:start -->"));
  });
});

test("map --write preserves manual changelog entries", async () => {
  await withLogRepo(async (tempDir) => {
    const logResult = runCli(tempDir, ["log", "Fixed auth routing", "--files", "src/auth.ts"]);
    const mapResult = runCli(tempDir, ["map", "--write"]);
    const content = await readFile(path.join(tempDir, "docs", "ai-context", "CHANGE_LOG.md"), "utf8");

    assert.equal(logResult.status, 0);
    assert.equal(mapResult.status, 0);
    assert.match(content, /Fixed auth routing/);
    assert.match(content, /`repo-context-center map --write`/);
  });
});

test("log dry-run does not write changelog", async () => {
  await withLogRepo(async (tempDir) => {
    const before = await readFile(path.join(tempDir, "docs", "ai-context", "CHANGE_LOG.md"), "utf8");
    const result = runCli(tempDir, ["log", "Preview only", "--dry-run"]);
    const after = await readFile(path.join(tempDir, "docs", "ai-context", "CHANGE_LOG.md"), "utf8");

    assert.equal(result.status, 0);
    assert.equal(result.stdout, "Would update docs/ai-context/CHANGE_LOG.md\n");
    assert.equal(after, before);
  });
});
