import path from "node:path";
import { pathExists, readTextFile, writeTextFile } from "../../core/fileSystem";
import { generatedEnd, generatedStart, handoffPath } from "./handoffConstants";
import { renderHandoffText } from "./renderText";
import type { HandoffBrief } from "./handoffTypes";

function renderGeneratedHandoff(brief: HandoffBrief): string {
  return [
    generatedStart,
    "## Generated Handoff",
    "",
    renderHandoffText(brief).trim(),
    "",
    "_Generated by repo-context-center. Edit outside this section._",
    generatedEnd
  ].join("\n");
}

export function upsertGeneratedHandoffSection(existing: string | null, brief: HandoffBrief): string {
  const section = renderGeneratedHandoff(brief);

  if (!existing || existing.trim().length === 0) {
    return `# Agent Handoff\n\n${section}\n`;
  }

  const start = existing.indexOf(generatedStart);
  const end = existing.indexOf(generatedEnd);

  if (start !== -1 && end !== -1 && end > start) {
    const before = existing.slice(0, start).trimEnd();
    const after = existing.slice(end + generatedEnd.length).trimStart();
    return `${before}\n\n${section}${after ? `\n\n${after.trimEnd()}` : ""}\n`;
  }

  return `${existing.trimEnd()}\n\n${section}\n`;
}

export async function writeHandoffBrief(cwd: string, brief: HandoffBrief): Promise<string> {
  const fullPath = path.join(cwd, handoffPath);
  const existing = await pathExists(fullPath) ? await readTextFile(fullPath) : null;
  const nextContent = upsertGeneratedHandoffSection(existing, brief);

  await writeTextFile(fullPath, nextContent);

  return handoffPath;
}
