import {
  repositoryLearningLimits,
  type RepositoryLearningModel
} from "./repositoryLearning";

export const repositoryLearningGeneratedStart = "<!-- repo-context-center:repository-learning:start -->";
export const repositoryLearningGeneratedEnd = "<!-- repo-context-center:repository-learning:end -->";

const legacyGeneratedStart = "<!-- repo-context-center:generated:start -->";
const legacyGeneratedEnd = "<!-- repo-context-center:generated:end -->";

const noneDetected = "none detected yet";
const populatedTogetherFallback = "observed together in completed work";

function cleanCell(value: string | null | undefined): string {
  return (value?.replace(/\r?\n/g, " ").replace(/\s+/g, " ").trim() || noneDetected)
    .replace(/\|/g, "\\|");
}

function codeCell(value: string): string {
  return `\`${cleanCell(value).replace(/`/g, "")}\``;
}

function limited<T>(values: T[], limit: number): T[] {
  return values.slice(0, limit);
}

function noneBullet(): string[] {
  return [`- ${noneDetected}`];
}

function noneTableRow(columns: number): string {
  return `| ${[noneDetected, ...Array.from({ length: columns - 1 }, () => "-")].join(" | ")} |`;
}

function table(headers: string[], rows: string[]): string[] {
  return [
    `| ${headers.join(" | ")} |`,
    `| ${headers.map((header) => header === "Count" ? "---:" : "---").join(" | ")} |`,
    ...rows
  ];
}

export function renderRepositoryLearningBody(model: RepositoryLearningModel): string {
  const relationshipRows = limited(model.commonFileRelationships, repositoryLearningLimits.commonFileRelationships)
    .map((relationship) => `| ${cleanCell(relationship.source)} | ${codeCell(relationship.related)} | ${cleanCell(relationship.reason)} | ${relationship.count} |`);
  const togetherRows = limited(model.frequentlyModifiedTogether, repositoryLearningLimits.frequentlyModifiedTogether)
    .map((item) => `| ${item.files.map(codeCell).join(", ")} | ${item.count} | ${cleanCell(item.recentSummary ?? populatedTogetherFallback)} |`);
  const verificationRows = limited(model.verificationPatterns, repositoryLearningLimits.verificationPatterns)
    .map((pattern) => `| ${cleanCell(pattern.scope)} | ${codeCell(pattern.command)} | ${pattern.count} |`);

  return [
    "## Recent Focus Areas",
    "",
    ...(model.recentFocusAreas.length > 0
      ? limited(model.recentFocusAreas, repositoryLearningLimits.recentFocusAreas).map((area) => `- ${cleanCell(area)}`)
      : noneBullet()),
    "",
    "## Common File Relationships",
    "",
    ...table(["Source", "Related", "Reason", "Count"], relationshipRows.length > 0 ? relationshipRows : [noneTableRow(4)]),
    "",
    "## Frequently Modified Together",
    "",
    ...table(["Files", "Count", "Recent summary"], togetherRows.length > 0 ? togetherRows : [noneTableRow(3)]),
    "",
    "## Verification Patterns",
    "",
    ...table(["Scope", "Command", "Count"], verificationRows.length > 0 ? verificationRows : [noneTableRow(3)]),
    "",
    "## Repository Habits",
    "",
    ...(model.repositoryHabits.length > 0
      ? limited(model.repositoryHabits, repositoryLearningLimits.repositoryHabits).map((habit) => `- ${cleanCell(habit)}`)
      : noneBullet())
  ].join("\n");
}

function renderGeneratedRepositoryLearning(model: RepositoryLearningModel): string {
  return [
    repositoryLearningGeneratedStart,
    "## Generated Repo Map",
    "",
    renderRepositoryLearningBody(model),
    "",
    "_Generated by repo-context-center. Edit outside this section._",
    repositoryLearningGeneratedEnd
  ].join("\n");
}

export function renderRepositoryLearning(model: RepositoryLearningModel): string {
  return [
    "# Repository Learning",
    "",
    "Compact learned repository behavior from completed RCC work.",
    "",
    renderGeneratedRepositoryLearning(model),
    ""
  ].join("\n");
}

export function upsertRepositoryLearning(existing: string | undefined, model: RepositoryLearningModel): string {
  const generated = renderGeneratedRepositoryLearning(model);

  if (!existing || existing.trim().length === 0) {
    return renderRepositoryLearning(model);
  }

  const normalized = existing.replace(/\r\n/g, "\n");
  let start = normalized.indexOf(repositoryLearningGeneratedStart);
  let end = normalized.indexOf(repositoryLearningGeneratedEnd);
  let endMarker = repositoryLearningGeneratedEnd;

  if (start === -1 || end === -1 || end <= start) {
    start = normalized.indexOf(legacyGeneratedStart);
    end = normalized.indexOf(legacyGeneratedEnd);
    endMarker = legacyGeneratedEnd;
  }

  if (start !== -1 && end !== -1 && end > start) {
    const before = normalized.slice(0, start).trimEnd();
    const after = normalized.slice(end + endMarker.length).trimStart();
    return `${before}\n\n${generated}${after ? `\n\n${after.trimEnd()}` : ""}\n`;
  }

  return `${normalized.trimEnd()}\n\n${generated}\n`;
}
